"""User-facing neural network namespace."""

from dlkit.domain.nn import (
    FFNN,
    SPDFFNN,
    DeepONet,
    DualPathFFNN,
    EmbeddedDeepONet,
    EmbeddedFactorizedFFNN,
    EmbeddedFFNN,
    EmbeddedParametricFFNN,
    EmbeddedSimpleFactorizedFFNN,
    EmbeddedSimpleParametricFFNN,
    EmbeddedSimpleSPDFactorizedFFNN,
    EmbeddedSimpleSPDFFNN,
    EmbeddedSPDFactorizedFFNN,
    EmbeddedSPDFFNN,
    FactorizedFFNN,
    FactorizedLinearNetwork,
    FFNNDeepONet,
    FiLMBlock,
    FiLMEmbeddedFFNN,
    FiLMFFNN,
    FiLMResidualBlock,
    FourierAugmented,
    FourierEnhancedFFNN,
    FourierFeatureNetwork,
    FourierNeuralOperator1d,
    GatedConvolutionBlock1d,
    GatedDeconvolutionBlock1d,
    GatedMLP,
    GLUGate,
    GridOperatorBase,
    GRNGate,
    HashEncodingNetwork,
    IGatingMechanism,
    IGridOperator,
    IOperatorNetwork,
    IQueryOperator,
    ISpectralLayer,
    LinearNetwork,
    ModifiedMLP,
    ParametricDenseBlock,
    ScaleEquivariantEmbeddedFactorizedFFNN,
    ScaleEquivariantEmbeddedSimpleFactorizedFFNN,
    ScaleEquivariantEmbeddedSimpleSPDFactorizedFFNN,
    ScaleEquivariantEmbeddedSimpleSPDFFNN,
    ScaleEquivariantEmbeddedSPDFactorizedFFNN,
    ScaleEquivariantEmbeddedSPDFFNN,
    ScaleEquivariantFactorizedFFNN,
    ScaleEquivariantFFNN,
    ScaleEquivariantFiLMEmbeddedFFNN,
    ScaleEquivariantFiLMFFNN,
    ScaleEquivariantFourierFeatureNetwork,
    ScaleEquivariantModifiedMLP,
    ScaleEquivariantSimpleFactorizedFFNN,
    ScaleEquivariantSimpleSPDFactorizedFFNN,
    ScaleEquivariantSimpleSPDFFNN,
    ScaleEquivariantSiren,
    ScaleEquivariantSPDFactorizedFFNN,
    ScaleEquivariantSPDFFNN,
    ScaleEquivariantVarWidthFiLMFFNN,
    SimpleFactorizedFFNN,
    SimpleSPDFactorizedFFNN,
    SimpleSPDFFNN,
    Siren,
    SPDFactorizedFFNN,
    SPDFactorizedLinearNetwork,
    SPDLinearNetwork,
    SpectralDualPath,
    SwiGLUGate,
    SymmetricFactorizedLinearNetwork,
    SymmetricLinearNetwork,
    UVGate,
    VarWidthDeepONet,
    VarWidthFFNN,
    VarWidthFiLMFFNN,
    attention,
    cae,
    encoder,
    ffnn,
    operators,
    primitives,
    spectral,
)

__all__ = [
    "LinearNetwork",
    "FactorizedLinearNetwork",
    "SymmetricLinearNetwork",
    "SPDLinearNetwork",
    "SymmetricFactorizedLinearNetwork",
    "SPDFactorizedLinearNetwork",
    "VarWidthFFNN",
    "FFNN",
    "EmbeddedFFNN",
    "GatedMLP",
    "FiLMBlock",
    "FiLMEmbeddedFFNN",
    "FiLMFFNN",
    "FiLMResidualBlock",
    "VarWidthFiLMFFNN",
    # ScaleEquivariant dense variants (variable-width)
    # ScaleEquivariant dense variants (constant-width)
    "ScaleEquivariantFFNN",
    "ScaleEquivariantFiLMFFNN",
    "ScaleEquivariantFiLMEmbeddedFFNN",
    "ScaleEquivariantVarWidthFiLMFFNN",
    # Plain dense variants
    # Constrained low-level builders
    "ParametricDenseBlock",
    "EmbeddedParametricFFNN",
    "EmbeddedSimpleParametricFFNN",
    # Embedded SPD variants (all-SPD, square)
    "EmbeddedSPDFFNN",
    "EmbeddedSimpleSPDFFNN",
    "EmbeddedSPDFactorizedFFNN",
    "EmbeddedSimpleSPDFactorizedFFNN",
    # Non-embedded SPD variants (all-SPD, square)
    "SPDFFNN",
    "SimpleSPDFFNN",
    "SPDFactorizedFFNN",
    "SimpleSPDFactorizedFFNN",
    # Embedded Factorized variants
    "EmbeddedFactorizedFFNN",
    "EmbeddedSimpleFactorizedFFNN",
    # Non-embedded Factorized variants
    "FactorizedFFNN",
    "SimpleFactorizedFFNN",
    # Scale-equivariant embedded SPD variants
    "ScaleEquivariantEmbeddedSPDFFNN",
    "ScaleEquivariantEmbeddedSimpleSPDFFNN",
    "ScaleEquivariantEmbeddedSPDFactorizedFFNN",
    "ScaleEquivariantEmbeddedSimpleSPDFactorizedFFNN",
    # Scale-equivariant non-embedded SPD variants
    "ScaleEquivariantSPDFFNN",
    "ScaleEquivariantSimpleSPDFFNN",
    "ScaleEquivariantSPDFactorizedFFNN",
    "ScaleEquivariantSimpleSPDFactorizedFFNN",
    # Scale-equivariant Factorized variants
    "ScaleEquivariantEmbeddedFactorizedFFNN",
    "ScaleEquivariantEmbeddedSimpleFactorizedFFNN",
    "ScaleEquivariantFactorizedFFNN",
    "ScaleEquivariantSimpleFactorizedFFNN",
    # Spectral / frequency-domain networks
    "ISpectralLayer",
    "FourierAugmented",
    "SpectralDualPath",
    "FourierEnhancedFFNN",
    "DualPathFFNN",
    "FourierFeatureNetwork",
    "HashEncodingNetwork",
    "Siren",
    "ModifiedMLP",
    "ScaleEquivariantFourierFeatureNetwork",
    "ScaleEquivariantSiren",
    "ScaleEquivariantModifiedMLP",
    # Neural operators
    "IOperatorNetwork",
    "IGridOperator",
    "IQueryOperator",
    "GridOperatorBase",
    "FourierNeuralOperator1d",
    "DeepONet",
    "VarWidthDeepONet",
    "FFNNDeepONet",
    "EmbeddedDeepONet",
    # Gating mechanisms and gated building blocks
    "IGatingMechanism",
    "GLUGate",
    "SwiGLUGate",
    "GRNGate",
    "UVGate",
    "GatedConvolutionBlock1d",
    "GatedDeconvolutionBlock1d",
    # Submodules
    "attention",
    "cae",
    "encoder",
    "ffnn",
    "operators",
    "primitives",
    "spectral",
]
