"""Checkpoint security configuration for PyTorch 2.6+ weights_only loading.

This module handles checkpoint loading for DLKit, which uses Pydantic settings
that contain type references and nested objects. Since we control the checkpoint
source (our own training code), we disable weights_only for trusted checkpoints.
"""

import os
from typing import Any, cast


def configure_checkpoint_loading() -> None:
    """Configure PyTorch to allow loading DLKit checkpoints with Pydantic settings.

    DLKit checkpoints contain Pydantic settings with nested objects and type references.
    Since these checkpoints are generated by our own trusted code, we disable the
    weights_only restriction for checkpoint loading.

    This is safe because:
    1. Checkpoints are created by DLKit's own training code (trusted source)
    2. Checkpoints are typically stored locally or in controlled environments
    3. Alternative approaches (registering all possible classes) are impractical
       due to nested settings and dynamic types

    Note: This sets TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD=1, which only affects
    checkpoint loading when weights_only is not explicitly specified.
    """
    # Set environment variable to disable weights_only for checkpoint loading
    # This is the recommended approach when loading from trusted sources
    os.environ.setdefault("TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD", "1")


def register_dlkit_safe_globals() -> None:
    """Register all DLKit classes that may appear in Lightning checkpoints as safe globals.

    PyTorch 2.6+ changed the default `weights_only=True` for `torch.load()`, which
    prevents unpickling of custom classes by default for security. This function
    registers all Pydantic settings and data entry classes used in DLKit checkpoints.

    This should be called before loading any Lightning checkpoints.

    Raises:
        ImportError: If torch is not available (handled gracefully)
        AttributeError: If torch.serialization.add_safe_globals doesn't exist (PyTorch < 2.6)
    """
    try:
        import torch.serialization

        # Import all settings classes that may be pickled in checkpoints
        from dlkit.infrastructure.config.core.base_settings import (
            BasicSettings,
            ComponentSettings,
            HyperParameterSettings,
        )
        from dlkit.infrastructure.config.data_entries import (
            AutoencoderTarget,
            Latent,
            PathFeature,
            PathTarget,
            Prediction,
            ValueFeature,
            ValueTarget,
        )
        from dlkit.infrastructure.config.model_components import (
            LossComponentSettings,
            MetricComponentSettings,
            ModelComponentSettings,
            WrapperComponentSettings,
        )
        from dlkit.infrastructure.config.optimizer_settings import (
            OptimizerSettings,
            SchedulerSettings,
        )

        # Collect all classes to register
        safe_classes: list[type[Any]] = [
            # Base settings classes
            BasicSettings,
            ComponentSettings,
            HyperParameterSettings,
            # Component settings
            WrapperComponentSettings,
            ModelComponentSettings,
            LossComponentSettings,
            MetricComponentSettings,
            OptimizerSettings,
            SchedulerSettings,
            # Data entry classes
            PathFeature,
            PathTarget,
            ValueFeature,
            ValueTarget,
            Latent,
            AutoencoderTarget,
            Prediction,
        ]

        # Register all classes as safe for unpickling
        torch.serialization.add_safe_globals(cast(Any, safe_classes))

    except ImportError, AttributeError:
        # Older PyTorch versions don't have add_safe_globals - safe to ignore
        # or torch not installed yet
        pass
