name: Test

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:python${{ matrix.python-version }}-bookworm-slim
    strategy:
      matrix:
        python-version: ["3.13", "3.14"]

    steps:
      - uses: actions/checkout@v5

      - name: Cache uv artifacts
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: linux-uv-python-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: linux-uv-python-${{ matrix.python-version }}-

      - name: Synchronize dependencies
        run: uv sync --dev

      - name: Run pytest
        run: uv run pytest tests --maxfail=1 --disable-warnings -vv

  test-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: latest

      - name: Set up Python
        run: uv python install 3.14

      - name: Synchronize dependencies
        run: uv sync --dev

      - name: Run pytest
        shell: bash
        run: uv run pytest tests --maxfail=1 --disable-warnings -vv
