name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.13", "3.14"]
        extra: ["",  "gpu"]
        exclude:
          - os: macos-latest
            extra: gpu

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: latest

      - name: Cache uv artifacts
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: ${{ runner.os }}-uv-python-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Synchronize dependencies
        shell: bash
        run: |
          if [[ "${{ matrix.extra }}" != "" ]]; then
            uv sync --dev --extra ${{ matrix.extra }}
          else
            uv sync --dev
          fi

      - name: Run pytest
        shell: bash
        run: |
          set -o pipefail
          uv run pytest tests --maxfail=1 --disable-warnings -vv
